[package]
name = "neural-net-fun"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rayon = "1.10.0"

[package.metadata.android.activity_attributes]
"android:exported" =  "true"
